import { BoardResponse } from '@/types/boardType';

export const COMMUNITY_BOARD: BoardResponse = {
  code: 'SUCCESS',
  message: '성공',
  data: {
    content: [
      {
        boardId: 351,
        title: '짱구는 못말려',
        code: '<body> <div> <h2>짱구는 못말려</h2> </div> <div> <i>철수</i>야 나랑 놀자 </div> </body>',
        oneLineContent: '짱구는 못말려철수야 나랑 놀자',
        nickName: '테스트유저1',
        createdAt: new Date(),
        imageUrl:
          'https://duaily-content.s3.ap-northeast-2.amazonaws.com/laptops-593296_1920%202.png',
        commentCount: 1,
        category: 'TREND',
        prefixCategory: 'INTRO',
      },
      {
        boardId: 352,
        title: '짱구는 못말려',
        code: '<body> <div> <h2>짱구는 못말려</h2> </div> <div> <i>철수</i>야 나랑 놀자 </div> </body>',
        oneLineContent: '짱구는 못말려철수야 나랑 놀자',
        nickName: '테스트유저1',
        createdAt: new Date(),
        imageUrl:
          'https://duaily-content.s3.ap-northeast-2.amazonaws.com/laptops-593296_1920%202.png',
        commentCount: 1,
        category: 'TREND',
        prefixCategory: 'INTRO',
      },
      {
        boardId: 353,
        title: '짱구는 못말려',
        code: '<body> <div> <h2>짱구는 못말려</h2> </div> <div> <i>철수</i>야 나랑 놀자 </div> </body>',
        oneLineContent: '짱구는 못말려철수야 나랑 놀자',
        nickName: '테스트유저1',
        createdAt: new Date(),
        imageUrl:
          'https://duaily-content.s3.ap-northeast-2.amazonaws.com/laptops-593296_1920%202.png',
        commentCount: 1,
        category: 'TREND',
        prefixCategory: 'INTRO',
      },
      {
        boardId: 354,
        title: '짱구는 못말려',
        code: '<body> <div> <h2>짱구는 못말려</h2> </div> <div> <i>철수</i>야 나랑 놀자 </div> </body>',
        oneLineContent: '짱구는 못말려철수야 나랑 놀자',
        nickName: '테스트유저1',
        createdAt: new Date(),
        imageUrl:
          'https://duaily-content.s3.ap-northeast-2.amazonaws.com/laptops-593296_1920%202.png',
        commentCount: 1,
        category: 'TREND',
        prefixCategory: 'INTRO',
      },
      {
        boardId: 355,
        title: '짱구는 못말려',
        code: '<body> <div> <h2>짱구는 못말려</h2> </div> <div> <i>철수</i>야 나랑 놀자 </div> </body>',
        oneLineContent: '짱구는 못말려철수야 나랑 놀자',
        nickName: '테스트유저1',
        createdAt: new Date(),
        imageUrl:
          'https://duaily-content.s3.ap-northeast-2.amazonaws.com/laptops-593296_1920%202.png',
        commentCount: 1,
        category: 'TREND',
        prefixCategory: 'INTRO',
      },
      {
        boardId: 356,
        title: '짱구는 못말려',
        code: '<body> <div> <h2>짱구는 못말려</h2> </div> <div> <i>철수</i>야 나랑 놀자 </div> </body>',
        oneLineContent: '짱구는 못말려철수야 나랑 놀자',
        nickName: '테스트유저1',
        createdAt: new Date(),
        imageUrl:
          'https://duaily-content.s3.ap-northeast-2.amazonaws.com/laptops-593296_1920%202.png',
        commentCount: 1,
        category: 'TREND',
        prefixCategory: 'INTRO',
      },
      {
        boardId: 357,
        title: '짱구는 못말려',
        code: '<body> <div> <h2>짱구는 못말려</h2> </div> <div> <i>철수</i>야 나랑 놀자 </div> </body>',
        oneLineContent: '짱구는 못말려철수야 나랑 놀자',
        nickName: '테스트유저1',
        createdAt: new Date(),
        commentCount: 1,
        category: 'TREND',
        prefixCategory: 'INTRO',
      },
      {
        boardId: 358,
        title: '짱구는 못말려',
        code: '<body> <div> <h2>짱구는 못말려</h2> </div> <div> <i>철수</i>야 나랑 놀자 </div> </body>',
        oneLineContent: '짱구는 못말려철수야 나랑 놀자',
        nickName: '테스트유저1',
        createdAt: new Date(),
        commentCount: 1,
        category: 'TREND',
        prefixCategory: 'INTRO',
      },
    ],
    pageable: {
      sort: {
        empty: true,
        unsorted: true,
        sorted: false,
      },
      offset: 0,
      pageNumber: 0,
      pageSize: 20,
      unpaged: false,
      paged: true,
    },
    last: true,
    totalPages: 12,
    totalElements: 1,
    sort: {
      empty: true,
      unsorted: true,
      sorted: false,
    },
    number: 0,
    first: true,
    size: 20,
    numberOfElements: 1,
    empty: false,
  },
};
